#pragma once
#include "../../DataManager/BaseDataType/CommonData/CommonData.h"

enum PanelInfoFileColumn
{
	COLUMN_ORDER_ID = 0,
	COLUMN_CABINET_ID = 1,
	COLUMN_BARCODE = 2, 
	COLUMN_CABINET_NAME = 3, 
	COLUMN_PANEL_NAME = 4,
	COLUMN_MATERIAL = 5, 
	COLUMN_CARVING_LEN = 6,
	COLUMN_CARVING_WIDTH = 7, 
	COLUMN_CARVING_THICKNESS = 8,
	COLUMN_COUNT = 9,	
	COLUMN_TEXTURE = 10, 
	COLUMN_BANDING_FRONT = 11,
	COLUMN_BANDING_RIGHT = 12,
	COLUMN_BANDING_BACK = 13,
	COLUMN_BANDING_LEFT = 14,
	COLUMN_OTHER_SHAPE_PARAM = 15,
	COLUMN_ROTATE_FLAG = 16,
	COLUMN_UP_FACE_SLOT = 17,
	COLUMN_SLOT_FLIP_FLAG = 18,
	COLUMN_DOWNER_FACE_SLOT = 19,
	COLUMN_UP_FACE_VHOLE = 20,
	COLUMN_VHOLE_FLIP_FLAG = 21,
	COLUMN_DOWN_FACE_VHOLE = 22,
	COLUMN_CUSTOMER_INFO = 23,
	COLUMN_JOINED_STORE = 24,
	COLUMN_SLOTTING_FLAG = 25,
	COLUMN_REMINDER = 26,
	COLUMN_DRILLING = 27,
	COLUMN_ORDER_TYPE = 28,
	COLUMN_REVERSE_SIDE_BARCODE = 29,
	COLUMN_PRODUCT_LEN = 30,
	COLUMN_PRODUCT_WIDTH = 31,
	COLUMN_PRODUCT_THICKNESS = 32,
	COLUMN_OTHER_SHAPE_ID = 33,
	COLUMN_CUSTOMER_ADDRESS = 34,
	COLUMN_HOLE_SLOT_FLAG = 35,
	COLUMN_OTHER_SHAPE_POINT = 36,
	COLUMN_SENDING_DATE = 37
	};

class AFX_EXT_CLASS ExcelReadWrite
{
public:
	static bool  ReadPanelInfo(LPCTSTR szFileDir, vector<ComponentInputItem>& vComponentInputItem, SourceFilePreProccesParam& param);

};
