#pragma once

//enum ORDER{ORDER_CLOCKWISE, ORDER_ANTICLOCKWISE};
//
//enum BringHHoleToUpperFaceType{NOT_BRING = 0, BRING_WHEN_HAS_INFO_IN_UPPER_FACE, BRING_ALWAYS};
//
//#define FACE_NO_UPPER 0
//#define FACE_NO_DOWNER 5
//
//enum MachineType{MACHINE_TYPE_H = 0, MACHINE_TYPE_FIVE_FACE};
//
//enum SourceDataType{SOURCE_DATA_TYPE_NCDATA = 0, SOURCE_DATA_TYPE_CADDATA};
//
//enum SawToMachiningSlotType{SAW_TO_MACHININING_SLOT_NEVER = 0, SAW_TO_MACHININING_SLOT_THROUGH_ONLY, SAW_TO_MACHININING_SLOT_ALL};
//
//enum DirVHType{DIR_UNKNOWN, DIR_H, DIR_V};

enum MillingOffsetDir{MILLING_OFFSET_DIR_NO, MILLING_OFFSET_DIR_LEFT, MILLING_OFFSET_DIR_RIGHT};

enum OutlineMachiningType{OUTLINE_NORMAL, OUTLINE_MILLING};

//enum PanelFaceTransType{TRANS_TYPE_ROTATE_180, TRANS_TYPE_CLOCKWISE_90, TRANS_TYPE_ANTI_CLOCKWISE_90, TRANS_TYPE_FLIP_H, TRANS_TYPE_FLIP_V};

//enum MachiningType{VHOLE, HHOLE, SLOT, MILLING_OUTLINE};

enum LineType{UNKNOWN = 0, STRAIGHT_LINE, CIRCULAR_ARC};

enum DirectionType{PLATE = 0, ANTI_CLOCKWISE, CLOCKWISE};

//enum ThroughSlotType{THROUGH_SLOT_TYPE_NO, THROUGH_SLOT_TYPE_THROUGH, THROUGH_SLOT_TYPE_START_ONLY, THROUGH_SLOT_TYPE_END_ONLY};

//enum TextureType{TEXTURE_NONE, TEXTURE_H, TEXTURE_V};
enum OutlineGroupType{OUTLINE_GROUP_TYPE_LINK, OUTLINE_GROUP_TYPE_START, OUTLINE_GROUP_TYPE_END};

//enum PanelDiagramPrintingStyle{PRINT_STYLE_A4_1, PRINT_STYLE_A4_4, PRINT_STYLE_LABEL};
//
//enum TextureDirectionType{TEXTURE_NO_DIR, TEXTRUE_H_DIR, TEXTURE_V_DIR};
//
//enum BandingID{BANDING_ID_FRONT = 0, BANDING_ID_RIGHT, BANDING_ID_BACK, BANDING_ID_LEFT};
//
//enum SideType{SIDE_LEFT, SIDG_BOTTOM, SIDE_RIGHT, SIDE_TOP};
//
//enum VertexType{LEFT_TOP, LEFT_BOTTOM, RIGHT_BOTTOM, RIGHT_TOP};
//
//enum LabelPosType{LABEL_POS_CENTER, LABEL_POS_LEFTTOP, LABEL_POS_RIGHTTOP, LABEL_POS_LEFTBOTTOM, LABEL_POS_RIGHTBOTTOM};
//
////enum ComponentType{COMPONENT_TYPE_REMAINDER, COMPONENT_TYPE_COMPONENT, COMPONENT_TYPE_COMBINED};
//enum RequirementListColumn
//{
//	LIST_COLUMN_ORDER_ID = 0,
//	LIST_COLUMN_CABINET_ID = 1,
//	LIST_COLUMN_BARCODE = 2, 
//	LIST_COLUMN_CABINET_NAME = 3, 
//	LIST_COLUMN_PANEL_NAME = 4,
//	LIST_COLUMN_MATERIAL = 5, 
//	LIST_COLUMN_CARVING_LEN = 6,
//	LIST_COLUMN_CARVING_WIDTH = 7, 
//	LIST_COLUMN_CARVING_THICKNESS = 8,
//	LIST_COLUMN_COUNT = 9,	
//	LIST_COLUMN_TEXTURE = 10, 
//	LIST_COLUMN_BANDING_FRONT = 11,
//	LIST_COLUMN_BANDING_RIGHT = 12,
//	LIST_COLUMN_BANDING_BACK = 13,
//	LIST_COLUMN_BANDING_LEFT = 14,
//	LIST_COLUMN_OTHER_SHAPE_PARAM = 15,
//	LIST_COLUMN_ROTATE_FLAG = 16,
//	LIST_COLUMN_UP_FACE_SLOT = 17,
//	LIST_COLUMN_SLOT_FLIP_FLAG = 18,
//	LIST_COLUMN_DOWNER_FACE_SLOT = 19,
//	LIST_COLUMN_UP_FACE_VHOLE = 20,
//	LIST_COLUMN_VHOLE_FLIP_FLAG = 21,
//	LIST_COLUMN_DOWN_FACE_VHOLE = 22,
//	LIST_COLUMN_CUSTOMER_INFO = 23,
//	LIST_COLUMN_JOINED_STORE = 24,
//	LIST_COLUMN_SLOTTING_FLAG = 25,
//	LIST_COLUMN_REMINDER = 26,
//	LIST_COLUMN_DRILLING = 27,
//	LIST_COLUMN_ORDER_TYPE = 28,
//	LIST_COLUMN_REVERSE_SIDE_BARCODE = 29,
//	LIST_COLUMN_PRODUCT_LEN = 30,
//	LIST_COLUMN_PRODUCT_WIDTH = 31,
//	LIST_COLUMN_PRODUCT_THICKNESS = 32,
//	LIST_COLUMN_OTHER_SHAPE_ID = 33,
//	LIST_COLUMN_CUSTOMER_ADDRESS = 34,
//	LIST_COLUMN_HOLE_SLOT_FLAG = 35,
//	LIST_COLUMN_OTHER_SHAPE_POINT = 36
//};
//
//extern char* g_aRequirementListTitle[37];
//extern char* g_aRequirementListTitle_ENU[37];
//extern char* g_aLabelMachineName[17];
